package com.inowak.infrastructure;

public enum NetworkCommands {
    READY,
    SEND_PASSWORD,
    ACCESS_GRANTED,
    ACCESS_DENIED,
    SEND_FILE_LIST,
    SENDING_FILE_LIST,
    SENDING_FILE_PATH,
    SENDING_FILE_HASH,
    RECEIVE_FILES_FROM_CLIENT,
    SENDING_FINISHED,
    SEND_FILE_PATH,
    SEND_FILE_SIZE,
    SEND_FILE_HASH,
    SEND_FILE,
    SEND_FILES_TO_CLIENT,
    RECEIVING_FINISHED,
    SENDING_FILE_SIZE,
    SENDING_FILE,
    SEND_FILE_TIME,
    SENDING_FILE_ABSOLUTE_PATH,
    DELETE_FILE_FROM_SERVER,

    NOT_RECOGNISED,
    EXIT
    ;
}
